import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/Home/Navbar/ResponsiveNav";
import Footer from "@/components/Home/Footer/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["200", "300"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="tr" className={inter.variable}>
      <body className="min-h-screen flex flex-col">
        <ResponsiveNav />

        <main className="flex-1 pt-[calc(10vh+40px)]">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
